"""Regenerate tests/target_schema.sql from the target column export (analysis/inputs).

The export has no enum labels or indexes, so the order_type_name enum uses
example labels and the chunk-column indexes are added explicitly.
"""
from pathlib import Path

import openpyxl

HERE = Path(__file__).parent
SRC = HERE.parent / "analysis" / "inputs" / "target_postgres_columns.xlsx"

ws = openpyxl.load_workbook(SRC, read_only=True).worksheets[0]
rows = list(ws.iter_rows(values_only=True))
head = rows[0]
cols = [dict(zip(head, r)) for r in rows[1:] if r[0]]

out = ["-- Generated by make_target_ddl.py from the target column export. Test fixture only.",
       "DROP SCHEMA IF EXISTS master CASCADE;", "CREATE SCHEMA master;",
       "CREATE TYPE master.order_type_name AS ENUM ('Dine In', 'Take Out', 'Delivery', 'Drive Thru', 'Catering');"]
tables = {}
for c in cols:
    tables.setdefault(c["table_name"], []).append(c)
for t, cs in tables.items():
    lines, pk = [], []
    for c in sorted(cs, key=lambda c: int(c["column_id"])):
        dt, lp = c["data_type"], c["length_precision"]
        if dt == "character varying":
            typ = f"varchar({lp})"
        elif dt == "numeric":
            typ = f"numeric({lp})"
        elif dt == "USER-DEFINED":
            typ = "master.order_type_name"
        elif dt.startswith("timestamp"):
            typ = dt
        else:
            typ = dt
        d = c["default_value"]
        if d and d != "(null)":
            if d.startswith("nextval("):
                seq = d.split("'")[1]
                out.append(f"CREATE SEQUENCE master.{seq};")
                d = f"nextval('master.{seq}'::regclass)"
            typ += f" DEFAULT {d}"
        if str(c["is_nullable"]).lower() == "false":
            typ += " NOT NULL"
        name = c["column_name"]
        lines.append(f'    "{name}" {typ}')
        if str(c["is_primary_key"]).lower() == "true":
            pk.append(f'"{name}"')
    if pk:
        lines.append(f"    PRIMARY KEY ({', '.join(pk)})")
    out.append(f"CREATE TABLE master.{t} (\n" + ",\n".join(lines) + "\n);")
for t, c in [("pos_orders", "end_day"), ("pos_order_details", "end_day"), ("pos_order_payments", "end_day"),
             ("employee_pay_summary", "pay_date"), ("weekly_cogs", "id")]:
    if t != "weekly_cogs":
        out.append(f"CREATE INDEX ON master.{t} ({c});")
(HERE / "target_schema.sql").write_text("\n".join(out) + "\n")
print("wrote target_schema.sql")
